### ISSUE TITLE
#5 edit page: add new category

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#10]
## Value Proposition
As a user, I want to add new categories, when i edit a list-item so that i can create new categories, even if i don't add a new list-item
## Description
![user-story-05](https://user-images.githubusercontent.com/85338528/196192503-2b6c8a4d-3b27-4994-a521-0b2d93cce78c.png)
## Acceptance Criteria
- [ ] show Input field with new category (edit-entry page)
## Tasks
- [x] create feature `feat/edit-list-item-new-category`
- [x] add new `Input component` (add new category) (on edit page)
  - [x] save the new category with the list-item inside localStorage & useState

**Comment by CathrinTruchan** [comment]
Nice!
