### ISSUE TITLE
#9 list-page: drag list items

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#11]
## Value Proposition
As a user, I want to change the order of each list-item inside a category so that i can sort these however i like them
## Description
![user-story-09](https://user-images.githubusercontent.com/85338528/198831220-0b2fe3c4-e706-4f5c-b516-46f25bc95bae.png)
## Acceptance Criteria
- [ ] show drag icon
- [ ] list items can be rearragend by dragging them to another position
## Tasks
- [x] create feature `feat/drag-list-items`
- [x] add `Icon component` (drag)
- [x] add `position in category` to the list-item
- [x] add the `category list-items count` as default value, if a new list-item is created inside a category
- [x] create a function to update the `position in category` on "drag end"

**Comment by F-Kirchhoff** [comment]
LGTM, you could rewrite the second AC: 'list items can be rearragend by dragging them to another position'
