### ISSUE TITLE
#6 edit page: delete entrys

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#16]
## Value Proposition
As a user, I want to have the ability to delete single list-items so that i can organize my categories.
## Description
![user-story-06](https://user-images.githubusercontent.com/85338528/197407334-3b185238-7717-4a58-b80a-b2b650ea5541.png)
## Acceptance Criteria
- [ ] show delete button (edit-entry page)
- [ ] show overlay for list-item deletion
## Tasks
- [x] create feature `feat/edit-list-item-delete`

**edit-entry page**
- [x] add `Button component` (delete)
- [x] create an blurry overlay with a `Modal-Box component` for the delete functionality
  - [x] add warning text
  - [x] add two `Button components`(back & delete)
- [x] add an click handler on the delete button to open the overlay
- [x] create a function (on the overlay delete button) to update the list-items inside the localStorage & the Store

**Comment by sebsch1337** [comment]
Looks good! What you're creating there is a modal. You could write "modal" instead of "overlay". Additionally you could add a task for the blur-filter, that overlays the background - that actually looks very nice :)
