### ISSUE TITLE
#7 edit category page

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#17]
## Value Proposition
As a user, I'd like to edit all categories, so that i can change their names
## Description
![user-story-07](https://user-images.githubusercontent.com/85338528/197408319-77078abf-99ec-411d-b60d-a61eca4884b1.png)
## Acceptance Criteria
- [ ] show edit button (list page)
  - [ ] on click show edit mask for this category
    - [ ] show input with category name
    - [ ] show back & save buttons
## Tasks
- [x] create feature `feat/edit-category`

**edit category page**
- [x] create a new page with a dynamic route `/edit-category/"categoryID"`
  - [x] add the `Header component` with text `Kateg. bearbeiten`
  - [x] add `Input component` with current category headline as value
  - [x] add two `Button components` (back & save)
    - [x] create a function (on the back button) to redirect to the list-page
    - [x] create a function (on the save button) to update the category inside the categories (localStorage & GlobalStore)

**list page**
- [x] add `Icon component` (edit) to each category headline
  - [x] add a click event which redirects to the edit-category page with the respective category

**Comment by sebsch1337** [comment]
Maybe you could write the value proposition more precise? As a user, I'd like to edit all categories **so that i can change their names**

I think the edit-page as a modal would be pretty cool :)
