### ISSUE TITLE
#8 edit category page: delete category 💥

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#18]
## Value Proposition
As a user, I'd like to delete categories so i can remove unneeded categories
## Description
![user-story-08](https://user-images.githubusercontent.com/85338528/197409522-3a748175-dd31-439f-836e-719c4848c68f.png)
## Acceptance Criteria
- [ ] show a delete button
  - [ ] open an overlay for the delete functionality (on click)
- [ ] list-items of the category sorted into a standard-category
## Tasks
- [x] add a `Button Component` (delete)
- [x] edit the "back" Button to small ([reference to last user-story](https://github.com/philmetscher/capstone-project/issues/17))
- [x] create an blurry overlay with a hidden `Modal-Box component` for the delete functionality
  - [x] add warning text
  - [x] add two `Button components`(back & delete)
- [x] add an click handler on the delete button to open the `Modal-Box component`
- [x] create a function (on the overlay delete button) to:
  - [x] change the category of the list items belonging to this category to the default category
  (default category described in [#7 edit-category-page](https://github.com/philmetscher/capstone-project/issues/17))
  - [x] update the categories inside the localStorage & the Store

**Comment by sebsch1337** [comment]
Noice. You could also write here "modal component" instead of "overlay".
