### ISSUE TITLE
#11 input-field: user notifications

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#25]
## Value Proposition
As a user I would expect to get a notification when I enter something wrong or not expected in an input field.
## Description
![user-story-11](https://user-images.githubusercontent.com/85338528/199066559-23de19a0-b9a6-4571-9d35-3fe6ff155d06.png)
## Acceptance Criteria
- [ ] show info messages with the corresponding info
## Tasks
- [x] create feature `feat/info-messages`
- [x] add a new component: `Info component`
- [x] add several messages for edit/create page of a list-item & a category (if the current Issue is set):
  - [ ] #1 `An entry cannot begin with a space`
  - [ ] #2 `A  category cannot begin with a space`
  - [x] #3 `This Entry already exist`
  - [x] #4 `This Category already exist`
- [ ] hide those messages after three seconds

**Comment by Mark-Krensel** [comment]
Personally I think 3 seconds is a bit long for these messages.
Idea: Instead of viewing a message with ```cannot begin with a space``` you could just cut i out when saving the item?

**Comment by philmetscher** [comment]
@Mark-Krensel thanks for the suggestion. I'll look how many seconds i need for each info.
I'll add the Idea instead of the message. Thanks 🙏
