### ISSUE TITLE
#12 multiple lists

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#26]
## Value Proposition
As a user I would like to have multiple lists to store different entries (for example todos, shopping etc.)
## Description
![user-story-12](https://user-images.githubusercontent.com/85338528/199069243-ca413916-3a4c-4f12-8bbe-1d9f2e00d087.png)
## Acceptance Criteria
- [ ] show overview page
- [ ] show list page with the corresponding data, when i click on a list headline
- [ ] show a back button inside the nav
## Tasks
- [x] create feature `feat/multiple-lists`
- [x] create a overview page
- [x] create `OverviewListEntry component`
- [x] add example-data for lists and map over them with the `OverviewListEntry component` (on the overview page)
- [x] add references to each list on each `OverviewListEntry component`
- [x] add a `NavLink component` (back to Lists) for the nav

**Comment by Mark-Krensel** [comment]
is ```OverviewListEntry```really a component or rather a page ?

**Comment by philmetscher** [comment]
@Mark-Krensel a component inside the `lists` page
