### ISSUE TITLE
#15 list-overview-page: drag lists

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#35]
## Value Proposition
As a user I would like to be able to sort my lists by drag & drop
## Description
![user-story-15](https://user-images.githubusercontent.com/85338528/200526115-da2b26dd-96e8-41d0-bb00-9c1c1f646a14.png)
## Acceptance Criteria
- [ ] show drag icon
- [ ] list items can be rearragend by dragging them to another position
## Tasks
- [x] create feature `feat/drag-lists`
- [x] add `Icon component` (drag)
- [x] add `position in category` to each list
- [x] add the `category list-items count` as default value, if a new list-item is created inside a category
- [x] create a function to update the `position in category` on "drag end"
