### ISSUE TITLE
#16 list-detail-page: check list-items

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#36]
## Value Proposition
As a user I would like to have the possibility to check off list entries so that I don't have to delete them but can use them again
## Description
![user-story-16](https://user-images.githubusercontent.com/85338528/200535558-c9b1a2a8-527c-45a6-b7fe-423ba81f0e1b.png)
## Acceptance Criteria
- [ ] list-items can be disabled, when clicked on the name
- [ ] onclick: displays the disabled list-item inside a disabled category
- [ ] disabled categories are listed below the active categories

## Tasks
- [x] create feature `feat/check-list-items`

**list-item**
- [ ] add an event handler (click) on the name of the list-item
- [ ] add a function that adds the same category (disabled one) of the list-item to the list and moves the list-item there

**disabled list-item**
- [ ] add an event handler (click) on the name of the list-item
- [ ] add a function that moves the list-item back to the active category and deletes the "deactivated" category
(if this category does not contain any deactivated list-items anymore)

**Comment by PhilippWeiss85** [comment]
Hey Phil,

I think you should update your ACs a bit so that they are not written so technical.
(e.g. List items can be disabled, displays the disabled list item category, disabled list items are sorted below the active items.....)
Otherwise fine!

**Comment by philmetscher** [comment]
> Hey Phil,
> 
> I think you should update your ACs a bit so that they are not written so technical. (e.g. List items can be disabled, displays the disabled list item category, disabled list items are sorted below the active items.....) Otherwise fine!

@PhilippWeiss85 i edited it a bit. User-Stories are hard to write for me 😅
