### ISSUE TITLE
#18 localStorage -> mongoDB

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#38]
## Value Proposition
As a user, I would like to be able to access the lists from anywhere, so I can manage them from more than just one device
## Description
All the logic that currently runs on the localStorage must be adapted to the database.
## Acceptance Criteria
- [ ] The data should be stored, deleted, updated and edited in the database
## Tasks
- [x] create feature `feat/database`
- [x] create new database & collection
- [x] insert example data into the collection
- [x] create file `.env.local` to set URI of MongoDB
- [x] create `dbConnect.js` inside `lib folder` to set the connection
- [ ] add models folder/files
- [ ] implement get / set / remove features to `useStore.js`
