### ISSUE TITLE
#3 List Overview Page

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#4]
## Value Proposition
As a user, I want to see some lists in the List Overview Page and a Action Bar
## Description
![List Overview](https://user-images.githubusercontent.com/85338528/195843785-09463c1c-03c9-4287-a655-d3fd8ea2a1dc.png)
## Acception Criteria
- [ ] headline
- [ ] lists
- [ ] action bar
## Tasks
- [ ] add a headline with specific site text
- [ ] add lists with static JSON-Data
- [ ] add action-bar for current nav-entry & "add list"-btn
