### ISSUE TITLE
#17 list-overview-page: list-item counter

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#40]
## Value Proposition
As a user it would be nice if I'm able to see in the list overview how many list entries are already finished
## Description
![user-story-17](https://user-images.githubusercontent.com/85338528/200797135-5fe03a23-8835-49c9-9c8f-52af1fb2778f.png)
## Acceptance Criteria
- [ ] show counter with list-items done / list-items not done
## Tasks
- [x] create feature `feat/list-items-counter`
- [x] add a `counter` state in the list
- [x] update the `counter` state, if any `list-item` gets checked / unchecked / deleted / created

**Comment by PhilippWeiss85** [comment]
Hey Phil,
lgtm.
