### ISSUE TITLE
#1 add first content

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#5]
## Value Proposition
As a User, I want a overview for all my lists
## Description
![list-overview](https://user-images.githubusercontent.com/85338528/195865562-7909fe51-2ab6-463c-b7dc-72d110a2fd92.png)
## Acception Criteria
- [ ] example content inside the list-overview
## Tasks
- [ ] add all icons as font
- [ ] create a list-overview page
- [ ] add Logo & headline in header
- [ ] add example JSON-Data with Lists inside the list-overview page
