### ISSUE TITLE
#1 the first simple list

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#6]
## Value Proposition
As a user, I need a list with categories, which i can extend or collapse.
Also i'd like to have list-items inside the categories, so i can see my todos/shopping list/....
## Description
![user-story-01](https://user-images.githubusercontent.com/85338528/196119192-5fc27ba7-ae6c-4e6d-85bc-b6af753e18c6.png)
## Acceptance Criteria
- [x] show logo with headline
- [x] show example data with categories & category-entrys
## Tasks
- [x] create feature `feat/simple-list`
- [x] add icon (logo & chevron icon) as font
- [x] add header with logo & list headline
- [x] map example extendable categories with example category-entries

**Comment by PhilippWeiss85** [comment]
Heyho! I think your the userstory is quite good and clean. If the category entries are an array you could maybe add another task e.g. "map example array". Otherwise is would think, that you are going to write hardcoded example data.

**Comment by Mark-Krensel** [comment]
Took me some time to understand your value proposition. Try to write it for 3rd-graders. I like the scope of your user story :)

**Comment by philmetscher** [comment]
> Took me some time to understand your value proposition. Try to write it for 3rd-graders. I like the scope of your user story :)

Thank you. I edited the value proposition :)
