### ISSUE TITLE
#2 create list-items

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#7]
## Value Proposition
As a user I want to create new list items so that i can create new todos/shopping items...
## Description
![user-story-02](https://user-images.githubusercontent.com/85338528/196120561-f2fa8536-ae8e-47f2-afd7-58deb49cefaf.png)
## Acceptance Criteria
- [ ] show button for adding entries
- [ ] add link to create-entry page
- [ ] create new page with a form to add new entries, which can be categorized
## Tasks
- [x] create feature `feat/new-list-item`
- [x] add `Button component` (add entries) and display it on the list-page
- [x] add routing (for create-entry page)
- [x] create new page (create-entry page)
  - [x] add a form
    - [x] add `Input component` (list-entry-name)
    - [x] add `Dropdown component` (with all categories)
    - [x] add two `Button components` (back, create)
    - [x] save list items in localStorage

**Comment by Mark-Krensel** [comment]
Maybe a bit much for 1 story. think about creating a form first, which is just underneath your main page and where you write the input inside.
I think navigation should be one user story of its own.

**Comment by F-Kirchhoff** [comment]
Hey Phil, looking very good already, please explicitly specify which elements are gonna be new components in your app and which are components you reuse (for example do you create 3 or 2 button components for this user story?)

**Comment by philmetscher** [comment]
Thanks. I changed some Acceptance Criteria & Tasks
