### ISSUE TITLE
#3 create categories

### ISSUE THREAD

**Issue by philmetscher** [philmetscher/capstone-project#8]
## Value Proposition
As a user, I also want to create categories so that i can sort my list-items inside of them.
## Description
![user-story-03](https://user-images.githubusercontent.com/85338528/196148454-24b6e131-28c6-47cb-883b-253680b7cc0f.png)
**Category-List Example for localStorage & useState:**
```javascript
[
  {
    id: 'A1259d6j6s',
    name: 'Haushalt'
  },
  {
    id: 'B6ghu86j6s',
    name: 'Haustiere'
  }
]
```

## Acceptance Criteria
- [x] (create-entry page) display input-field to insert a new category
- [x] save the data, so i can reload and get all inserted data
## Tasks
- [x] create feature `feat/new-category`
- [x] add new `Input component` (insert new category) inside the create-entry page
- [x] save the list-items & categories localStorage and useState

**Comment by AHen-C0de** [comment]
Do you save the new Category in an extra category useState to be re-usable?
Is the localStorage updated according to the useState?
Please specify..

**Comment by philmetscher** [comment]
> Do you save the new Category in an extra category useState to be re-usable? Is the localStorage updated according to the useState? Please specify..

I edited a example-list how i store my localStorage & useState
